# Site
name: ""
title_suffix: ""
title: ""
description: ""
meta_description: ""
logo: ''
favicon: "/assets/images/favicon.ico"
baseurl: "https://www.howtoplaysport.com"
permalink: /:categories/:title
email: ""
google_analytics: ""

# Authors
authors:
  reece:
    name: Reece
    display_name: Reece Williams
    gravatar:
    email: ""
    description: ""
